rm(list = ls())
X_obs = read.csv("~/Desktop/UCD/TransFD/Data/IID/Simulation/HighDim_E/dense/w_error/X_obs.csv", header=FALSE)
T_obs = read.csv("~/Desktop/UCD/TransFD/Data/IID/Simulation/HighDim_E/dense/w_error/T_obs.csv", header=FALSE)
True_data = read.csv("~/Desktop/UCD/TransFD/Data/IID/Simulation/HighDim_E/X_full_true.csv", header=FALSE)
X_imputed_DSA <- read.csv("~/Desktop/UCD/TransFD/ImputedData/IID/Simulation/HighDim_E/DiffSelfAtt/dense/w_error/X_imputed_l2w.csv", header=FALSE)
X_imputed_l2w <- read.csv("~/Desktop/UCD/TransFD/ImputedData/IID/Simulation/HighDim_E/Vanilla/dense/w_error/X_imputed_l2w.csv", header=FALSE)
X_imputed_l1w <- read.csv("~/Desktop/UCD/TransFD/ImputedData/IID/Simulation/HighDim_E/Vanilla/dense/w_error/X_imputed_l1w.csv", header=FALSE)
X_imputed_None <- read.csv("~/Desktop/UCD/TransFD/ImputedData/IID/Simulation/HighDim_E/Vanilla/dense/w_error/X_imputed_None.csv", header=FALSE)

DSA_X = as.vector(as.matrix(X_imputed_DSA[dim(X_imputed_DSA)[1], ]))
Vanilla_X = as.vector(as.matrix(X_imputed_None[dim(X_imputed_None)[1], ]))
l1w_X = as.vector(as.matrix(X_imputed_l1w[dim(X_imputed_l1w)[1], ]))
l2w_X = as.vector(as.matrix(X_imputed_l2w[dim(X_imputed_l2w)[1], ]))
true_curve = as.vector(as.matrix(True_data[dim(True_data)[1], ]))
obs = list(t = as.vector(as.matrix(T_obs[dim(T_obs)[1], ])), x = as.vector(as.matrix(X_obs[dim(X_obs)[1], ])))

time = seq(0, 1, length.out = 101)

linewidth = 4
plot(time, true_curve, type = "l", ylim = c(-2.5, 2), col = "darkgreen", lwd = linewidth, ylab = "", main = "Imputations of Different Methods", xlim = c(0.2, 0.7), cex.main = 1.8, xlab = "")
lines(time, l1w_X, col = "purple", lwd = linewidth)
lines(time, Vanilla_X, col = "orange", lwd = 2.5)
lines(time, DSA_X, col = "red", lwd = linewidth)
points(obs$t, obs$x[2:31], pch = 20, col = "blue", cex = 1.5)
legend("topright", legend = c("True Curve", "VT", "VT+l1w", "DSA", "Obs."), col = c("darkgreen", "orange", "purple", "red", "blue"), lty = c(1, 1, 1, 1, NA), pch = c(NA, NA, NA, NA, 20), lwd = 3)
